import type { MovieDetail } from "./schemas";

// Fallback dataset used when OMDB_API_KEY is not configured, so the app runs
// without the external API. Posters are "N/A" on purpose (UI shows a placeholder).
export const MOCK_MOVIES: MovieDetail[] = [
  {
    Response: "True",
    imdbID: "tt0133093",
    Title: "The Matrix",
    Year: "1999",
    Type: "movie",
    Rated: "R",
    Released: "31 Mar 1999",
    Runtime: "136 min",
    Genre: "Action, Sci-Fi",
    Director: "Lana Wachowski, Lilly Wachowski",
    Writer: "Lilly Wachowski, Lana Wachowski",
    Actors: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    Plot: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    Language: "English",
    Country: "United States",
    Awards: "Won 4 Oscars. 42 wins & 51 nominations total",
    Poster: "N/A",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.7/10" },
      { Source: "Rotten Tomatoes", Value: "83%" },
      { Source: "Metacritic", Value: "73/100" },
    ],
    Metascore: "73",
    imdbRating: "8.7",
    imdbVotes: "1,900,000",
  },
  {
    Response: "True",
    imdbID: "tt0816692",
    Title: "Interstellar",
    Year: "2014",
    Type: "movie",
    Rated: "PG-13",
    Released: "07 Nov 2014",
    Runtime: "169 min",
    Genre: "Adventure, Drama, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan",
    Actors: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
    Plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    Language: "English",
    Country: "United States, United Kingdom",
    Awards: "Won 1 Oscar. 44 wins & 148 nominations total",
    Poster: "N/A",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.7/10" },
      { Source: "Rotten Tomatoes", Value: "73%" },
    ],
    Metascore: "74",
    imdbRating: "8.7",
    imdbVotes: "2,100,000",
  },
  {
    Response: "True",
    imdbID: "tt0468569",
    Title: "The Dark Knight",
    Year: "2008",
    Type: "movie",
    Rated: "PG-13",
    Released: "18 Jul 2008",
    Runtime: "152 min",
    Genre: "Action, Crime, Drama",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan, David S. Goyer",
    Actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
    Plot: "When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest tests of his ability to fight injustice.",
    Language: "English",
    Country: "United States, United Kingdom",
    Awards: "Won 2 Oscars. 162 wins & 165 nominations total",
    Poster: "N/A",
    Ratings: [{ Source: "Internet Movie Database", Value: "9.0/10" }],
    Metascore: "84",
    imdbRating: "9.0",
    imdbVotes: "2,800,000",
  },
  {
    Response: "True",
    imdbID: "tt0109830",
    Title: "Forrest Gump",
    Year: "1994",
    Type: "movie",
    Rated: "PG-13",
    Released: "06 Jul 1994",
    Runtime: "142 min",
    Genre: "Drama, Romance",
    Director: "Robert Zemeckis",
    Writer: "Winston Groom, Eric Roth",
    Actors: "Tom Hanks, Robin Wright, Gary Sinise",
    Plot: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75.",
    Language: "English",
    Country: "United States",
    Awards: "Won 6 Oscars. 50 wins & 75 nominations total",
    Poster: "N/A",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.8/10" }],
    Metascore: "82",
    imdbRating: "8.8",
    imdbVotes: "2,200,000",
  },
  {
    Response: "True",
    imdbID: "tt0903747",
    Title: "Breaking Bad",
    Year: "2008–2013",
    Type: "series",
    Rated: "TV-MA",
    Released: "20 Jan 2008",
    Runtime: "49 min",
    Genre: "Crime, Drama, Thriller",
    Director: "N/A",
    Writer: "Vince Gilligan",
    Actors: "Bryan Cranston, Aaron Paul, Anna Gunn",
    Plot: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student.",
    Language: "English",
    Country: "United States",
    Awards: "Won 16 Primetime Emmys. 169 wins & 269 nominations total",
    Poster: "N/A",
    Ratings: [{ Source: "Internet Movie Database", Value: "9.5/10" }],
    Metascore: "N/A",
    imdbRating: "9.5",
    imdbVotes: "2,200,000",
    totalSeasons: "5",
  },
  {
    Response: "True",
    imdbID: "tt0944947",
    Title: "Game of Thrones",
    Year: "2011–2019",
    Type: "series",
    Rated: "TV-MA",
    Released: "17 Apr 2011",
    Runtime: "57 min",
    Genre: "Action, Adventure, Drama",
    Director: "N/A",
    Writer: "David Benioff, D.B. Weiss",
    Actors: "Emilia Clarke, Peter Dinklage, Kit Harington",
    Plot: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    Language: "English",
    Country: "United States, United Kingdom",
    Awards: "Won 59 Primetime Emmys. 390 wins & 633 nominations total",
    Poster: "N/A",
    Ratings: [{ Source: "Internet Movie Database", Value: "9.2/10" }],
    Metascore: "N/A",
    imdbRating: "9.2",
    imdbVotes: "2,300,000",
    totalSeasons: "8",
  },
  {
    Response: "True",
    imdbID: "tt1375666",
    Title: "Inception",
    Year: "2010",
    Type: "movie",
    Rated: "PG-13",
    Released: "16 Jul 2010",
    Runtime: "148 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan",
    Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
    Plot: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    Language: "English, Japanese, French",
    Country: "United States, United Kingdom",
    Awards: "Won 4 Oscars. 159 wins & 220 nominations total",
    Poster: "N/A",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.8/10" }],
    Metascore: "74",
    imdbRating: "8.8",
    imdbVotes: "2,500,000",
  },
  {
    Response: "True",
    imdbID: "tt0110912",
    Title: "Pulp Fiction",
    Year: "1994",
    Type: "movie",
    Rated: "R",
    Released: "14 Oct 1994",
    Runtime: "154 min",
    Genre: "Crime, Drama",
    Director: "Quentin Tarantino",
    Writer: "Quentin Tarantino, Roger Avary",
    Actors: "John Travolta, Uma Thurman, Samuel L. Jackson",
    Plot: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    Language: "English, Spanish, French",
    Country: "United States",
    Awards: "Won 1 Oscar. 70 wins & 75 nominations total",
    Poster: "N/A",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.9/10" }],
    Metascore: "95",
    imdbRating: "8.9",
    imdbVotes: "2,100,000",
  },
  {
    Response: "True",
    imdbID: "tt4154796",
    Title: "Avengers: Endgame",
    Year: "2019",
    Type: "movie",
    Rated: "PG-13",
    Released: "26 Apr 2019",
    Runtime: "181 min",
    Genre: "Action, Adventure, Drama",
    Director: "Anthony Russo, Joe Russo",
    Writer: "Christopher Markus, Stephen McFeely",
    Actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo",
    Plot: "After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos' actions and restore balance to the universe.",
    Language: "English, Japanese, Xhosa",
    Country: "United States",
    Awards: "Nominated for 1 Oscar. 70 wins & 133 nominations total",
    Poster: "N/A",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.4/10" }],
    Metascore: "78",
    imdbRating: "8.4",
    imdbVotes: "1,300,000",
  },
  {
    Response: "True",
    imdbID: "tt0137523",
    Title: "Fight Club",
    Year: "1999",
    Type: "movie",
    Rated: "R",
    Released: "15 Oct 1999",
    Runtime: "139 min",
    Genre: "Drama",
    Director: "David Fincher",
    Writer: "Chuck Palahniuk, Jim Uhls",
    Actors: "Brad Pitt, Edward Norton, Meat Loaf",
    Plot: "An insomniac office worker and a soap maker form an underground fight club that evolves into something much more.",
    Language: "English",
    Country: "United States, Germany",
    Awards: "Nominated for 1 Oscar. 11 wins & 38 nominations total",
    Poster: "N/A",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.8/10" }],
    Metascore: "67",
    imdbRating: "8.8",
    imdbVotes: "2,300,000",
  },
  {
    Response: "True",
    imdbID: "tt0114369",
    Title: "Se7en",
    Year: "1995",
    Type: "movie",
    Rated: "R",
    Released: "22 Sep 1995",
    Runtime: "127 min",
    Genre: "Crime, Drama, Mystery",
    Director: "David Fincher",
    Writer: "Andrew Kevin Walker",
    Actors: "Morgan Freeman, Brad Pitt, Kevin Spacey",
    Plot: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 1 Oscar. 29 wins & 44 nominations total",
    Poster: "N/A",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.6/10" }],
    Metascore: "65",
    imdbRating: "8.6",
    imdbVotes: "1,700,000",
  },
  {
    Response: "True",
    imdbID: "tt0167260",
    Title: "The Lord of the Rings: The Return of the King",
    Year: "2003",
    Type: "movie",
    Rated: "PG-13",
    Released: "17 Dec 2003",
    Runtime: "201 min",
    Genre: "Action, Adventure, Drama",
    Director: "Peter Jackson",
    Writer: "J.R.R. Tolkien, Fran Walsh, Philippa Boyens",
    Actors: "Elijah Wood, Viggo Mortensen, Ian McKellen",
    Plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom.",
    Language: "English, Quenya, Old English",
    Country: "New Zealand, United States",
    Awards: "Won 11 Oscars. 213 wins & 124 nominations total",
    Poster: "N/A",
    Ratings: [{ Source: "Internet Movie Database", Value: "9.0/10" }],
    Metascore: "94",
    imdbRating: "9.0",
    imdbVotes: "1,900,000",
  },
];
